#ifndef HI_CTYPES_H
#define HI_CTYPES_H

#define HI_RANGE_START  0x0900
#define HI_RANGE_END    0x097F

#define HI_UNDEF_T   0x0
#define HI_ALPHA_T   0x1
#define HI_DIGIT_T   0x2
#define HI_PUNCT_T   0x4
#define HI_INTERN_T  0x8
#define HI_OTHER_T   0x10


#define ishialpha(x) (isalpha(x) || ((x >= HI_RANGE_START && x <= HI_RANGE_END) ? hi_ctypes[x - HI_RANGE_START] & HI_ALPHA_T : 0))
#define ishidigit(x) (isdigit(x) || (x >= HI_RANGE_START && x <= HI_RANGE_END) ? hi_ctypes[x - HI_RANGE_START] & HI_DIGIT_T : 0)
#define ishipunct(x) (ispunct(x) || x == 0x0964 || x == 0x0965 || ((x >= HI_RANGE_START && x <= HI_RANGE_END) ? hi_ctypes[x - HI_RANGE_START] & HI_PUNCT_T : 0))
#define ishiintern(x) ((x >= HI_RANGE_START && x <= HI_RANGE_END) ? hi_ctypes[x - HI_RANGE_START] & HI_INTERN_T : 0)


static unsigned char hi_ctypes[] = {
/*     bn_undef        0x0980 */ HI_UNDEF_T,
/*     bn_chandrabindu 0x0981 */ HI_ALPHA_T,
/*     bn_anusvara     0x0982 */ HI_ALPHA_T,
/*     bn_visarga      0x0983 */ HI_ALPHA_T,
/*     bn_undef        0x0984 */ HI_UNDEF_T,
/*     bn_a            0x0985 */ HI_ALPHA_T,
/*     bn_aa           0x0986 */ HI_ALPHA_T,
/*     bn_i            0x0987 */ HI_ALPHA_T,
/*     bn_ii           0x0988 */ HI_ALPHA_T,
/*     bn_u            0x0989 */ HI_ALPHA_T,
/*     bn_uu           0x098a */ HI_ALPHA_T,
/*     bn_ri           0x098b */ HI_ALPHA_T,
/*     bn_undef        0x098c */ HI_UNDEF_T,
/*     bn_undef        0x098d */ HI_UNDEF_T,
/*     bn_undef        0x098e */ HI_UNDEF_T,
/*     bn_e            0x098f */ HI_ALPHA_T,
/*     bn_ai           0x0990 */ HI_ALPHA_T,
/*     bn_undef        0x0991 */ HI_UNDEF_T,
/*     bn_undef        0x0992 */ HI_UNDEF_T,
/*     bn_o            0x0993 */ HI_ALPHA_T,
/*     bn_au           0x0994 */ HI_ALPHA_T,
/*     bn_k            0x0995 */ HI_ALPHA_T,
/*     bn_kh           0x0996 */ HI_ALPHA_T,
/*     bn_g            0x0997 */ HI_ALPHA_T,
/*     bn_gh           0x0998 */ HI_ALPHA_T,
/*     bn_ng           0x0999 */ HI_ALPHA_T,
/*     bn_ch           0x099a */ HI_ALPHA_T,
/*     bn_chh          0x099b */ HI_ALPHA_T,
/*     bn_j            0x099c */ HI_ALPHA_T,
/*     bn_jh           0x099d */ HI_ALPHA_T,
/*     bn_n            0x099e */ HI_ALPHA_T,
/*     bn_tt           0x099f */ HI_ALPHA_T,
/*     bn_tth          0x09a0 */ HI_ALPHA_T,
/*     bn_dd           0x09a1 */ HI_ALPHA_T,
/*     bn_ddh          0x09a2 */ HI_ALPHA_T,
/*     bn_mn           0x09a3 */ HI_ALPHA_T,
/*     bn_t            0x09a4 */ HI_ALPHA_T,
/*     bn_th           0x09a5 */ HI_ALPHA_T,
/*     bn_d            0x09a6 */ HI_ALPHA_T,
/*     bn_dh           0x09a7 */ HI_ALPHA_T,
/*     bn_dn           0x09a8 */ HI_ALPHA_T,
/*     bn_undef        0x09a9 */ HI_UNDEF_T,
/*     bn_p            0x09aa */ HI_ALPHA_T,
/*     bn_ph           0x09ab */ HI_ALPHA_T,
/*     bn_b            0x09ac */ HI_ALPHA_T,
/*     bn_bh           0x09ad */ HI_ALPHA_T,
/*     bn_m            0x09ae */ HI_ALPHA_T,
/*     bn_J            0x09af */ HI_ALPHA_T,
/*     bn_r            0x09b0 */ HI_ALPHA_T,
/*     bn_undef        0x09b1 */ HI_UNDEF_T,
/*     bn_l            0x09b2 */ HI_ALPHA_T,
/*     bn_undef        0x09b3 */ HI_UNDEF_T,
/*     bn_undef        0x09b4 */ HI_UNDEF_T,
/*     bn_undef        0x09b5 */ HI_UNDEF_T,
/*     bn_sh           0x09b6 */ HI_ALPHA_T,
/*     bn_ss           0x09b7 */ HI_ALPHA_T,
/*     bn_s            0x09b8 */ HI_ALPHA_T,
/*     bn_h            0x09b9 */ HI_ALPHA_T,
/*     bn_undef        0x09ba */ HI_UNDEF_T,
/*     bn_undef        0x09bb */ HI_UNDEF_T,
/*     bn_nukta        0x09bc */ HI_INTERN_T,
/*     bn_undef        0x09bd */ HI_OTHER_T,
/*     bn_AA           0x09be */ HI_ALPHA_T,
/*     bn_I            0x09bf */ HI_ALPHA_T,
/*     bn_II           0x09c0 */ HI_ALPHA_T,
/*     bn_U            0x09c1 */ HI_ALPHA_T,
/*     bn_UU           0x09c2 */ HI_ALPHA_T,
/*     bn_RI           0x09c3 */ HI_ALPHA_T,
/*     bn_undef        0x09c4 */ HI_OTHER_T,
/*     bn_undef        0x09c5 */ HI_UNDEF_T,
/*     bn_undef        0x09c6 */ HI_UNDEF_T,
/*     bn_E            0x09c7 */ HI_ALPHA_T,
/*     bn_AI           0x09c8 */ HI_ALPHA_T,
/*     bn_undef        0x09c9 */ HI_UNDEF_T,
/*     bn_undef        0x09ca */ HI_UNDEF_T,
/*     bn_O            0x09cb */ HI_ALPHA_T,
/*     bn_AU           0x09cc */ HI_ALPHA_T,
/*     bn_hosh         0x09cd */ HI_INTERN_T,
/*     bn_khandata     0x09ce */ HI_ALPHA_T,
/*     bn_undef        0x09cf */ HI_UNDEF_T,
/*     bn_undef        0x09d0 */ HI_UNDEF_T,
/*     bn_undef        0x09d1 */ HI_UNDEF_T,
/*     bn_undef        0x09d2 */ HI_UNDEF_T,
/*     bn_undef        0x09d3 */ HI_UNDEF_T,
/*     bn_undef        0x09d4 */ HI_UNDEF_T,
/*     bn_undef        0x09d5 */ HI_UNDEF_T,
/*     bn_undef        0x09d6 */ HI_UNDEF_T,
/*     bn_undef        0x09d7 */ HI_UNDEF_T,
/*     bn_undef        0x09d8 */ HI_UNDEF_T,
/*     bn_undef        0x09d9 */ HI_UNDEF_T,
/*     bn_undef        0x09da */ HI_UNDEF_T,
/*     bn_undef        0x09db */ HI_UNDEF_T,
/*     bn_rr           0x09dc */ HI_ALPHA_T,
/*     bn_rrh          0x09dd */ HI_ALPHA_T,
/*     bn_undef        0x09de */ HI_UNDEF_T,
/*     bn_y            0x09df */ HI_ALPHA_T,
/*     bn_undef        0x09e0 */ HI_UNDEF_T,
/*     bn_undef        0x09e1 */ HI_UNDEF_T,
/*     bn_undef        0x09e2 */ HI_UNDEF_T,
/*     bn_undef        0x09e3 */ HI_UNDEF_T,
/*     bn_undef        0x09e4 */ HI_UNDEF_T,
/*     bn_undef        0x09e5 */ HI_UNDEF_T,
/*     bn_zero         0x09e6 */ HI_DIGIT_T,
/*     bn_one          0x09e7 */ HI_DIGIT_T,
/*     bn_two          0x09e8 */ HI_DIGIT_T,
/*     bn_three        0x09e9 */ HI_DIGIT_T,
/*     bn_four         0x09ea */ HI_DIGIT_T,
/*     bn_five         0x09eb */ HI_DIGIT_T,
/*     bn_six          0x09ec */ HI_DIGIT_T,
/*     bn_seven        0x09ed */ HI_DIGIT_T,
/*     bn_eight        0x09ee */ HI_DIGIT_T,
/*     bn_nine         0x09ef */ HI_DIGIT_T,
/*     bn_undef        0x09f0 */ HI_UNDEF_T,
/*     bn_undef        0x09f1 */ HI_UNDEF_T,
/*     bn_undef        0x09f2 */ HI_OTHER_T,
/*     bn_undef        0x09f3 */ HI_OTHER_T,
/*     bn_undef        0x09f4 */ HI_OTHER_T,
/*     bn_undef        0x09f5 */ HI_OTHER_T,
/*     bn_undef        0x09f6 */ HI_OTHER_T,
/*     bn_undef        0x09f7 */ HI_OTHER_T,
/*     bn_undef        0x09f8 */ HI_OTHER_T,
/*     bn_undef        0x09f9 */ HI_OTHER_T,
/*     bn_undef        0x09fa */ HI_OTHER_T,
/*     bn_undef        0x09fb */ HI_UNDEF_T,
/*     bn_undef        0x09fc */ HI_UNDEF_T,
/*     bn_undef        0x09fd */ HI_UNDEF_T,
/*     bn_undef        0x09fe */ HI_UNDEF_T,
/*     bn_undef        0x09ff */ HI_UNDEF_T,
};

#endif
